### Example file for running REMS using docker image from DockerHub
# See docs/installing-upgrading.md for more info

version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rems
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://db:5432/rems?user=rems&password=remspassword
      AUTHENTICATION: :oidc
      oidc-domain: rems-staging.au.auth0.com
      oidc-client-id: 7XdPR343v6oyJq3e7BIZKz91HHbfdeAa
      oidc-client-secret: KHuGK1hOkoIALn2AmVXWTG3nopqsxniZGPsYeqGpHA2-E2kh_61lql2AxwcKPviw
      PUBLIC_URL: http://localhost:3000/
      mem_limit: 2000m
    ports:
      - "127.0.0.1:3000:3000"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: rems
      POSTGRES_PASSWORD: remspassword
    mem_limit: 150m
    ports:
      - "127.0.0.1:5432:5432"
